[tool.poetry]
name = "limapi"
version = "0.1.0"
description = "Lightweight api manager"
authors = ["Marsvest"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
